version: "3.9"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver_controle_estoque
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Senha123!"
      MSSQL_PID: "Express"
    ports:
      - "1434:1433"
    volumes:
      - estoque_data:/var/opt/mssql
    restart: unless-stopped

volumes:
  estoque_data: